### ISSUE TITLE
Some Typescript Love

### ISSUE THREAD

**Issue by devorbitus** [slackapi/bolt-js-getting-started-app#1]
This is a great start but would love to see another project that utilizes TypeScript and highlights how to properly type some of the event and web client API objects.

**Comment by mwbrooks** [comment]
Great suggestion, @devorbitus! I'd be interested in adding these sort of examples.

Are you looking for TypeScript examples using the Node SDK [slackapi/node-slack-sdk](https://github.com/slackapi/node-slack-sdk/tree/main/packages) or using the [Bolt JS](https://github.com/slackapi/bolt-js) framework?

**Comment by devorbitus** [comment]
Honestly, both. I'm writing a bit using Bolt but at times I need to type the objects using the imported slack web client merely for Typescript. The Bolt documentation on Typescript reads like it's about to cover a lot of material then only covers minimum version.

**Comment by mwbrooks** [comment]
@devorbitus We're going to turn off this getting started app's issue tracker and redirect issues to https://github.com/slackapi/bolt-js/issues under the label `area:examples`. We think this will ensure that all the issues get the necessary attention and helps our team monitor fewer places.

You're not alone is wanting more Typescript love in the `node-slack-sdk` and `bolt-js` projects. If you have the time, I'd suggest creating an issue to create a discussion around what we can do. You may want want to checkout this pull request - I'm unsure if it'll be merged, but it was a team members attempt at adding more Typescript support: 
https://github.com/slackapi/node-slack-sdk/pull/1078/files

Thanks again for submitting the first issue to the Getting Started App! 🙌🏻
